from setuptools import setup, find_packages

setup(
    name="kimia_infer",
    version="0.1.7",
    description="Kimi-Audio inference and toolkit package.",
    author="Moonshot AI",
    packages=find_packages(),
    install_requires=[
        "torch>=2.4.1",
        "torchaudio>=2.4.1",
        "packaging",
        "jinja2",
        "openai-whisper",
        "jsonlines",
        "pandas",
        "validators",
        "sty",
        "transformers",
        "librosa",
        "accelerate",
        "aiohttp",
        "colorama",
        "omegaconf>=2.3.0",
        "sox",
        "six>=1.16.0",
        "hyperpyyaml",
        "conformer>=0.3.2",
        "diffusers",
        "pillow",
        "sentencepiece",
        "easydict",
        "fire",
        "ujson",
        "cairosvg",
        "immutabledict",
        "rich",
        "wget",
        "gdown",
        "datasets",
        "torchdyn>=1.0.6",
        "huggingface_hub",
        "loguru",
        "decord",
        "blobfile",
        "timm",
        "sacrebleu>=1.5.1",
        "soundfile",
        "tqdm"
    ],
    include_package_data=True,
    package_data={
        'kimia_infer.models.detokenizer.vocoder.alias_free_activation': [
            'cuda/*.h',
            'cuda/*.cu',
            'cuda/*.cpp'
        ],
        'kimia_infer.models.tokenizer.whisper_Lv3': ['*.npz']
    },
    python_requires=">=3.8",
)
