name: Build wheel

on:
  workflow_dispatch:
  push:
    branches:
      - cuda-build
  create:
    tags:
      - v*

jobs:
  build:
    permissions: write-all
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        # platform: [ubuntu-latest, windows-latest]
        platform: [windows-latest]
        python-version: ["3.10"]
        # cuda-version: ["12.4.0"]
        # fix due to missing 12.4.0 in the network
        # cuda-version: ["12.5.0"]
        cuda-version: ["12.4.1"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@v0.2.23
        with:
          cuda: ${{ matrix.cuda-version }}
          # method: network
          method: local
          sub-packages: '["nvcc", "cudart", "cusolver", "cublas", "curand", "cufft", "cusparse", "cupti", "thrust"]'
      - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false

          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false
          docker-images: false

      - name: Set CUDA paths for Linux
        if: runner.os == 'Linux'
        run: |
          echo "PATH=/usr/local/cuda-12.4/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV


      - name: Set CUDA paths for Windows
        if: runner.os == 'Windows'
        run: |
          echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;${env:PATH}" >> $env:GITHUB_ENV
          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" >> $env:GITHUB_ENV
          echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" >> $env:GITHUB_ENV

      # test if cuda_profiler_api.h exists
      - name: Check CUDA profiler_api.h on Linux
        if: runner.os == 'Linux'
        run: |
          if [ -f /usr/local/cuda-12.4/include/cuda_profiler_api.h ]; then
            echo "cuda_profiler_api.h exists"
          else
            echo "cuda_profiler_api.h does not exist"
            exit 1
          fi

      - name: Check CUDA profiler_api.h on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (Test-Path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include\cuda_profiler_api.h") {
            echo "cuda_profiler_api.h exists"
          } else {
            echo "cuda_profiler_api.h does not exist"
            exit 1
          }
        
      - name: Install Deps
        run: python -m pip install torch==2.6.0 wheel ninja build setuptools numpy --extra-index-url https://download.pytorch.org/whl/cu124
      
      - name: Install project depss
        run: python -m pip install --no-build-isolation -e .

      - name: Build the wheel
        env:
          TORCH_CUDA_ARCH_LIST: "7.0;8.0"  # Specify supported GPU architectures
          FORCE_CUDA: 1
          # Disable build isolation
          PIP_NO_BUILD_ISOLATION: "yes" 
        run: python -m build --wheel --no-isolation --outdir dist/

      - run: du -h dist/*
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl

      - name: Log Built Wheels
        run: |
          ls dist
  
      - name: Set wheel name
        run: echo "wheel_name=$(basename dist/*.whl)" >> $GITHUB_ENV
        
      - name: Get the tag version
        id: extract_branch
        run: echo ::set-output name=branch::${GITHUB_REF#refs/tags/}

      - name: Get Release with tag
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          tag_name: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_path: ./dist/${{env.wheel_name}}
          asset_name: ${{env.wheel_name}}
          asset_content_type: application/*
